### ISSUE TITLE
Check pip version

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/sphericart#12]
@Luthaf and I think we could do some version checking of pip. This would ensure that builds don't fail in silly ways due to simply having an old pip version

**Comment by Luthaf** [comment]
Unfortunately, that seems to be pretty much impossible: https://stackoverflow.com/questions/60068313/include-minimum-pip-version-in-setup-py

The standard way pip builds code, there is no pip module to import and check the version. So the best thing is to tell people to update their pip when they see weird building/installation errors.
