### ISSUE TITLE
pytorch example 

### ISSUE THREAD

**Issue by felixmusil** [lab-cosmo/sphericart#13]
Hi,

I installed with pip the library and the torch bindings (with a fresh conda environment with torch 2.0.0) and I run `python examples/pytorch/example.py --normalized` which gave the error:
```
Float vs double relative error: 3.25688027e-07
Check derivative difference: 0.0
torch.Size([1000, 121, 3]) torch.Size([1000, 3, 121])
Traceback (most recent call last):
  File "/home/musil/git/sphericart/examples/pytorch/example.py", line 108, in <module>
    sphericart_example(args.l, args.s, args.normalized)
  File "/home/musil/git/sphericart/examples/pytorch/example.py", line 78, in sphericart_example
    f"Check fw derivative difference CPU vs CUDA: {torch.norm(dsh_sphericart_cuda.to('cpu')-dsh_sphericart)}"
RuntimeError: The size of tensor a (3) must match the size of tensor b (121) at non-singleton dimension 2
```
As you can see, the gradients in the cpu/cuda implementation return shapes with swapped axis: `[cuda]torch.Size([1000, 121, 3]) [cpu]torch.Size([1000, 3, 121])`.

Do you also observe such behavior?

**Comment by Luthaf** [comment]
This was a bug, it should be fixed in https://github.com/lab-cosmo/sphericart/commit/43b4319dc72c928bb52d513e4b81aebdfa32a747

**Comment by nickjbrowning** [comment]
This should be resolved now - please open another issue if you encounter something :)
