### ISSUE TITLE
Can irregular spherical harmonics be added?

### ISSUE THREAD

**Issue by amunozj** [lab-cosmo/sphericart#134]
Hi! thank you so much for your implementation of sphericart.  I was wondering if you could add the irregular spherical harmonics?  I want to solve a problem outside of a sphere and the regular spherical harmonics blow up as you get away from the center.  

Thanks a lot!

**Comment by ceriottm** [comment]
We will soon open a PR to change a bit the API, to make it more homogeneous. In that context, even though this is an "opinionated" library that primarily targets real solid harmonics written in a Cartesian form, we would be happy to have "adapters" that compute other forms. We recently added an example https://sphericart.readthedocs.io/en/latest/spherical-complex.html of how to compute complex sph, for instance. Ideally, this should be done in a way that can be applied to any of the frontends. We'd be very happy to have something along these lines contributed.

**Comment by amunozj** [comment]
Thank you @ceriottm and @frostedoyster !  As I learned more about sphericart, I realized that I can build the irregular solid harmonics by simply using normalized sphericart harmonics and add the r^{-l} term to get the solid irregular harmonics.  Thank you so much for an awesome package!
