### ISSUE TITLE
installing pytorch bindings

### ISSUE THREAD

**Issue by felixmusil** [lab-cosmo/sphericart#62]
Hey, I am trying to install sphericart with pytorch bindings with GPU support on a cluster with: `pip install .[torch]` but it fails. After some debugging it turns out that in `sphericart/torch/pyproject.toml`, `torch` is required for installation but it is done in isolation by `pip` so it pulls the latest torch with cpu-only support (`2.0.1`). I am using an older version of pytorch (`1.13.1`) so the resulting library is not compatible hence the failure.

**Comment by Luthaf** [comment]
We need to implement some check mechanism like in [equistore-torch](https://github.com/lab-cosmo/equistore/blob/371a9e52952e80a6286916017b61264d7876a8d2/python/equistore-torch/equistore/torch/_c_lib.py#L36-L41) to give a better error message here.

In the mean time, your possibilities are to either update torch to the latest version, or disable build isolation (`pip install .[torch] --no-build-isolation` which will build against torch `1.13.1`).
